version: "3.7"

services:
  crafty:
    container_name: crafty_container
    image: registry.gitlab.com/crafty-controller/crafty-4:latest
    restart: unless-stopped

    ports:
      - "8443:8443"
      - "8000:8000"

    volumes:
      - ${APP_DATA_DIR}/config:/crafty/app/config
      - ${APP_DATA_DIR}/logs:/crafty/app/logs
      - ${APP_DATA_DIR}/servers:/crafty/app/servers
      - ${APP_DATA_DIR}/backups:/crafty/app/backups

    environment:
      - TZ=Europe/Madrid